#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin

NAME=my-flask-server
DAEMON=gunicorn
# 설치한 폴더명을 아래에 입력해 주세요. (기본값: /opt/apps/my-flask-server)
ROOT=/opt/apps/$NAME
ACTIVATE=$ROOT/venv/bin/activate

APPNAME=$NAME
APP=app:app
# 기본 포트 번호를 변경 후 외부 접속을 차단해주세요.
BIND=0.0.0.0:8181
WORKERS=1
LOGLEVEL=DEBUG
PIDFILE=/var/run/$DAEMON.pid
LOGFILE=/var/log/$DAEMON.log
SYS_LOG_ADDR=unix:///dev/log#dgram
MAX_REQUESTS=100

# instance/config.py 에서 사용할 정보를 입력해 주세요.
export GATHERMATE_AUTH_ID=admin
export GATHERMATE_AUTH_PW=password
export GATHERMATE_ETO_ID=
export GATHERMATE_ETO_PW=
export GATHERMATE_CINE_ID=
export GATHERMATE_CINE_PW=

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting gunicorn" "$APPNAME"
        source $ACTIVATE
        $DAEMON  $APP --daemon --chdir $ROOT --bind=$BIND --max-requests $MAX_REQUESTS --pid=$PIDFILE --workers=$WORKERS --log-file=$LOGFILE --log-level $LOGLEVEL --log-syslog-to $SYS_LOG_ADDR --log-syslog-prefix $APPNAME
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping gunicorn" "$APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac
