#!/bin/sh

PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

NAME=gathermate
ENABLED=yes
PROCS=gunicorn
DESC=$NAME
# 설치한 폴더명을 아래에 입력해 주세요. (기본값: /opt/apps/gathermate)
ROOT=/opt/apps/$NAME
ACTIVATE=$ROOT/venv/bin/activate
PRECMD="source $ACTIVATE"
PREARGS=

APP=app:app
# 기본 포트 번호를 변경 후 외부 접속을 차단해주세요.
BIND=0.0.0.0:8181
WORKERS=1
LOGLEVEL=ERROR
PIDFILE=/opt/var/run/$PROCS.pid
LOGFILE=/opt/var/log/$PROCS.log
SYS_LOG_ADDR=unix:///dev/log#dgram
SSL_CERT=
SSL_KEY=

ARGS="$APP --daemon --preload --chdir $ROOT -k gevent --bind=$BIND --workers=$WORKERS --certfile=$SSL_CERT --keyfile=$SSL_KEY --pid=$PIDFILE --log-file=$LOGFILE --log-level $LOGLEVEL --log-syslog-to $SYS_LOG_ADDR --log-syslog-prefix $NAME"

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TZ="$(cat /etc/TZ)"
export PYTHONIOENCODING=utf-8

# instance/config.py 에서 사용할 정보를 입력해 주세요.
export GATHERMATE_AUTH_ID=admin
export GATHERMATE_AUTH_PW=password
export GATHERMATE_ETO_ID=
export GATHERMATE_ETO_PW=
export GATHERMATE_CINE_ID=
export GATHERMATE_CINE_PW=

case ${1} in
    send)
        source $ACTIVATE
        cd $ROOT
        flask send "$2" "$3"
        exit $?
        ;;
esac

source /opt/etc/init.d/rc.func
